---
title: "Gov 50 Final Project"
author: Greta Candreva
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...

looking at if there is a relationship between the height of NHL players and the number of career goals they have (do shorter/taller players tend to score more goals/be more successful?). 


```{r}
library(tidyverse)
library(readr)


learning_pref <- read_csv("learning_pref.csv", show_col_types = FALSE)
learning_pref
```

How do remote vs. in-person learning preferences vary based on ethnicity, grade level, and gender? I hypothesize, that as grade level increases, preference for remote learning will increase. I do not think that gender will be an influential factor, and I do not think ethnicity will be an influential factor. I think that grade level will be the most influential factor, because I think that at a young age, in-person classes are very important for group discussions, class activities, and making friendships which all aid in a child's development. I think that as students get older, these types of activities are less common because they have acquired the necessary skills for completing activities on their own, making friends etc. Therefore, I think that as grade level increases, so will the preference for remote learning. My outcome variable is remote learning preference which is collected based off students who have attended school in-person at least once since September 16, 2020. My explanatory variables are gender (male or female), race (White, Asian, Black, Hispanic, Multi-Racial, Native American, Unknown), and grade level (PK, OK, 1-12). If I observe greater preference for remote learning in the higher grades, this would support my hypothesis. If I observe less preference for remote learning in higher grades, this would go against my hypothesis. Furthermore, if I observe no change in remote learning preference based on gender and race, this supports by hypothesis, while any changes will go against my hypothesis. When I run my regression of remote learning preference on the indicated variables, a positive, significant coefficient would indicate support for my hypothesis. 
